### ISSUE TITLE
Fhir resource init 409 error from fhir server

### ISSUE THREAD

**Issue by rti** [dot-base/fhir-server#222]
```
docker service logs -f xk5qkxj9dzvm
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | 
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | > fhir-resources@0.1.0 production:start
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | > npm run production:initialize; npm run production:migrate
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | 
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | 
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | > fhir-resources@0.1.0 production:initialize
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | > node -r tsconfig-paths/register build/resource-initializer/initialize.js
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | 
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | [Started] Initializing search parameters for modules: dotbase, dotlink, basic, parkinson, dbs, legacy
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | [Success] Initializing search parameters for modules: dotbase, dotlink, basic, parkinson, dbs, legacy
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | 
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | [Started] Initializing resources and sample resources for modules: dotbase, dotlink, basic, parkinson, dbs, legacy
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | 409 Conflict
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | {
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    |   "resourceType": "OperationOutcome",
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    |   "text": {
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    |     "status": "generated",
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    |     "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>HAPI-0550: could not execute batch; SQL [insert into trm_codesystem_ver (codesystem_pid, cs_display, cs_version_id, res_id, pid) values (?, ?, ?, ?, ?)]; constraint [idx_codesystem_and_ver]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute batch</pre></td>\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    |   },
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    |   "issue": [ {
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    |     "severity": "error",
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    |     "code": "processing",
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    |     "diagnostics": "HAPI-0550: could not execute batch; SQL [insert into trm_codesystem_ver (codesystem_pid, cs_display, cs_version_id, res_id, pid) values (?, ?, ?, ?, ?)]; constraint [idx_codesystem_and_ver]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute batch"
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    |   } ]
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | }
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | [Errored] Initializing resources and sample resources for modules: dotbase, dotlink, basic, parkinson, dbs, legacy:
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | Error: 409 Conflict
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    |     at FhirApi.executeBundle (/usr/src/project/build/api/fhir.js:55:19)
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    |     at async ResourceInitializer.initializeResources (/usr/src/project/build/resource-initializer/initialize.js:90:13)
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    |     at async ResourceInitializer.initialize (/usr/src/project/build/resource-initializer/initialize.js:60:9)
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | 
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | [Started] Initializing 1000 patients
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | [Success] Initializing 1000 patients
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | 
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | > fhir-resources@0.1.0 production:migrate
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | > node -r tsconfig-paths/register build/resource-migrations/migrate.js
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | 
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | Migration Fix wearing-off answer code system and value code
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | Collecting resources from server...
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | Collected 0 resources
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | Analyzing...
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | Need to update 0 resources
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | Need to delete 0 resources
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | Updating resources on server...
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | Done
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | 
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | Migration Add subject to section lists
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | Collecting resources from server...
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | Collected 0 resources
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | Analyzing...
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | Need to update 0 resources
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | Need to delete 0 resources
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | Updating resources on server...
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | Done
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | 
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | Draft action migrations already done. Nothing to do...
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | 
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | Migration Remove medication dosage unit questionnaire responses
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | Collecting resources from server...
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | Collected 0 resources
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | Analyzing...
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | Need to update 0 resources
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | Need to delete 0 resources
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | Updating resources on server...
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | Done
dotbase_fhir-resources.1.xk5qkxj9dzvm@docker-desktop    | 
```

**Comment by rti** [comment]
related? https://github.com/hapifhir/hapi-fhir/pull/4227

**Comment by rti** [comment]
is this related to https://github.com/dot-base/fhir-resources/issues/306 ?

**Comment by rti** [comment]
# TODO

Verify that the `fhir-resource` container exits with a failure when this bug happens and that docker restarts it automatically
