### ISSUE TITLE
HAPI-0389 hibernate.exception.LockAcquisitionException: could not execute batch

### ISSUE THREAD

**Issue by rti** [dot-base/fhir-server#227]
```
❱ docker exec -it $(docker ps -q -f name=dotbase_fhir-resources) npm start

> fhir-resources@0.1.0 start
> npm run initialize && npm run migrate


> fhir-resources@0.1.0 initialize
> node -r tsconfig-paths/register -r ts-node/register src/resource-initializer/initialize.ts

[Started] Initializing search parameters for modules: dotbase, dotlink, basic, parkinson, dbs, legacy
[Success] Initializing search parameters for modules: dotbase, dotlink, basic, parkinson, dbs, legacy

[Started] Initializing resources and sample resources for modules: dotbase, dotlink, basic, parkinson, dbs, legacy
500 Internal Server Error
{
  "resourceType": "OperationOutcome",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>HAPI-0389: Failed to call access method: org.springframework.dao.CannotAcquireLockException: could not execute batch; SQL [delete from trm_valueset where pid=?]; nested exception is org.hibernate.exception.LockAcquisitionException: could not execute batch</pre></td>\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
  },
  "issue": [ {
    "severity": "error",
    "code": "processing",
    "diagnostics": "HAPI-0389: Failed to call access method: org.springframework.dao.CannotAcquireLockException: could not execute batch; SQL [delete from trm_valueset where pid=?]; nested exception is org.hibernate.exception.LockAcquisitionException: could not execute batch"
  } ]
}
[Errored] Initializing resources and sample resources for modules: dotbase, dotlink, basic, parkinson, dbs, legacy:
Error: 500 Internal Server Error
    at Function.executeBundle (/var/workspace/src/api/fhir.ts:67:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ResourceInitializer.initializeResources (/var/workspace/src/resource-initializer/initialize.ts:110:7)
    at ResourceInitializer.initialize (/var/workspace/src/resource-initializer/initialize.ts:77:5)

> fhir-resources@0.1.0 migrate
> node -r tsconfig-paths/register -r ts-node/register src/resource-migrations/migrate.ts

Migration Fix wearing-off answer code system and value code
Collecting resources from server...
Collected 0 resources
Analyzing...
Need to update 0 resources
Need to delete 0 resources
Updating resources on server...
Done

Migration Add subject to section lists
Collecting resources from server...
Collected 0 resources
Analyzing...
Need to update 0 resources
Need to delete 0 resources
Updating resources on server...
Done

Draft action migrations already done. Nothing to do...

Migration Remove medication dosage unit questionnaire responses
Collecting resources from server...
Collected 0 resources
Analyzing...
Need to update 0 resources
Need to delete 0 resources
Updating resources on server...
Done
```

seen on fix/resource-dependencies branch on second resource init... too fast? still indexing?

**Comment by rti** [comment]
waiting for reindex to finish seems to fix it

**Comment by mecklenburg** [comment]
known issue, but currently not fixable from our side
